export enum EAppKeys {
  Tour = "Tour",
  Explorer = "Explorer",
  BasedFarm = "BasedFarm",
  Memesweeper = "Memesweeper",
  Error = "Error",
  Pepemail = "Pepemail",
  Wallet = "Wallet",
  Notepepe = "Notepepe",
  Wenpamp = "Wenpamp",
  PepePaint = "PepePaint",
  Uniswap = "Uniswap",
  Dextools = "Dextools",
  Frogger = "Frogger",
  GTA1 = "GTA1",
  // RedAlert = "RedAlert",
  Messenger = "Messenger",
  Zuma = "Zuma",
  KekBot = "KekBot",
  ChristmasClaims = "ChristmasClaims",
  UserPreferences = "UserPreferences",
}
